// src/pages/twin/ReportsPage.jsx
import React, { useEffect, useState } from 'react'
import DashboardLayout from '../../components/layout/DashboardLayout'
import Loader from '../../components/common/Loader'
import EmptyState from '../../components/common/EmptyState'
import Modal from '../../components/common/Modal'
import { getReports, generateReport, deleteReport } from '../../api/reportService'
import { getPatients } from '../../api/patientService'
import { useAuth } from '../../context/AuthContext'

const REPORT_TYPES = ['Summary', 'Vitals', 'Predictions', 'CarePlan']

export default function ReportsPage() {
  const { user } = useAuth()
  const canManage = user?.role === 'ADMIN' || user?.role === 'DOCTOR' || user?.role === 'RECEPTIONIST'
  const canDelete = user?.role === 'ADMIN' || user?.role === 'DOCTOR'

  const [reports, setReports] = useState(null)
  const [patients, setPatients] = useState([])
  const [selectedPatientId, setSelectedPatientId] = useState('')
  const [selectedType, setSelectedType] = useState('Summary')
  const [generating, setGenerating] = useState(false)
  const [viewingReport, setViewingReport] = useState(null)

  async function load() {
    const [reportData, patientData] = await Promise.all([getReports(), getPatients()])
    setReports(reportData)
    setPatients(patientData)
    setSelectedPatientId((prev) => prev || (patientData[0] ? String(patientData[0].id) : ''))
  }

  useEffect(() => { load() }, [])

  async function handleGenerate() {
    if (!selectedPatientId) return
    setGenerating(true)
    try {
      await generateReport(Number(selectedPatientId), selectedType)
      await load()
    } finally {
      setGenerating(false)
    }
  }

  async function handleDelete(id) {
    if (!window.confirm('Delete this report?')) return
    await deleteReport(id)
    await load()
  }

  return (
    <DashboardLayout title="Reports">
      <p className="text-muted mb-4">Generated point-in-time reports pulling together vitals, prescriptions, appointments, predictions and care plans.</p>

      {canManage && (
        <div className="ms-card p-3 p-md-4 mb-4">
          <h6 className="brand-font mb-3">Generate a new report</h6>
          <div className="d-flex flex-wrap gap-2 align-items-center">
            <select className="form-select" style={{ maxWidth: 260 }} value={selectedPatientId} onChange={(e) => setSelectedPatientId(e.target.value)}>
              {patients.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
            <select className="form-select" style={{ maxWidth: 180 }} value={selectedType} onChange={(e) => setSelectedType(e.target.value)}>
              {REPORT_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}
            </select>
            <button className="btn btn-primary" onClick={handleGenerate} disabled={generating || !selectedPatientId}>
              <i className="bi bi-file-earmark-plus me-1"></i> {generating ? 'Generating…' : 'Generate Report'}
            </button>
          </div>
        </div>
      )}

      <div className="ms-card p-2 p-md-3">
        {!reports ? (
          <Loader />
        ) : reports.length === 0 ? (
          <EmptyState icon="bi-file-earmark-bar-graph" title="No reports yet" subtitle="Generate one above to see it here." />
        ) : (
          <div className="table-responsive">
            <table className="table ms-table align-middle mb-0">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Type</th>
                  <th>Generated By</th>
                  <th>Generated At</th>
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r.id}>
                    <td className="fw-semibold">{r.title}</td>
                    <td>{r.type}</td>
                    <td>{r.generatedBy}</td>
                    <td className="ms-mono-cell">{r.generatedAt ? new Date(r.generatedAt).toLocaleString() : '—'}</td>
                    <td className="text-end">
                      <button className="btn btn-sm btn-outline-primary me-2" onClick={() => setViewingReport(r)}>
                        <i className="bi bi-eye me-1"></i> View
                      </button>
                      {canDelete && (
                        <button className="btn btn-sm btn-outline-danger" onClick={() => handleDelete(r.id)}>
                          <i className="bi bi-trash"></i>
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      <Modal show={!!viewingReport} title={viewingReport?.title || 'Report'} onClose={() => setViewingReport(null)}>
        <pre style={{
          whiteSpace: 'pre-wrap', background: 'var(--surface-raised)', border: '1px solid var(--line)',
          borderRadius: 8, padding: '0.9rem', color: 'var(--ink)', fontSize: '0.82rem', margin: 0,
        }}>{viewingReport?.content}</pre>
      </Modal>
    </DashboardLayout>
  )
}
